Repository International-Data-Spaces-Association/IDS-Messaging-Services, pull requests merged in 2021-06, with the labels that each got.

#127 App-Prop fields for Clearing-House Endpoints
  CHANGELOG.md
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseService.java
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/IDSClearingHouseService.java
  clearinghouse/src/test/resources/application.properties
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/orbiter/OrbiterTokenManagerService.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpServiceTest.java
Labels: Status: Under Review

#131 Add a Connector Blacklist, enforced when checking the DAT Token
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/DatValidationRule.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/ValidationRuleException.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/ValidationRuleResult.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifierTest.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcher.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcherProvider.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcherTest.java
Labels: Status: Under Review

#161 Release v4.1.1.0
  CHANGELOG.md
  README.md
  broker/pom.xml
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/BrokerService.java
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/IDSBrokerService.java
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/util/FullTextQueryTemplate.java
  broker/src/test/java/de/fraunhofer/ids/messaging/broker/BrokerServiceTest.java
  clearinghouse/pom.xml
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseService.java
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/IDSClearingHouseService.java
  clearinghouse/src/test/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseServiceTest.java
  clearinghouse/src/test/resources/application.properties
  core/pom.xml
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/DatValidationRule.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/ValidationRuleException.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/customvalidation/ValidationRuleResult.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/orbiter/OrbiterTokenManagerService.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifierTest.java
  messaging/pom.xml
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcher.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcherProvider.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/MessageController.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/InfrastructureService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/MessageService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/HttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverter.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/parser/MultipartDatapart.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/parser/MultipartParseException.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/parser/MultipartParser.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/parser/package-info.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/response/Base64EncodedFileBodyResponse.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/response/BodyResponse.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/response/ErrorResponse.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/util/InfomodelMessageBuilder.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcherTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/endpoint/MessageControllerTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/multipart/parser/MultipartParserTest.java
  pom.xml
Labels: Status: In Progress

#169 Optimize Test-Coverage
  CHANGELOG.md
  broker/lombok.config
  clearinghouse/lombok.config
  core/lombok.config
  core/pom.xml
  core/src/test/java/de/fraunhofer/ids/messaging/core/config/ConfigProducerTest.java
  core/src/test/resources/configmodel.json
  core/src/test/resources/ids-keystore.p12
  core/src/test/resources/keystore.p12
  messaging/lombok.config
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/response/ErrorResponse.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcherTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/testhandlers/NotificationMessageHandler.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/endpoint/EndpointServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/InfrastructureServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverterTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/response/MessageResponseTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/IdsMessageUtilsTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/InfomodelMessageBuilderTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/RequestUtilsTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/SerializerProviderTest.java
Labels: Status: Feedback Needed, Status: Pull-Request

#179 new UnknownResponseException, UnexpectedResponseException and DeserializeException
  CHANGELOG.md
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/BrokerService.java
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/IDSBrokerService.java
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseService.java
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/IDSClearingHouseService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/InfrastructureService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/MessageService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/UnexpectedResponseException.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/DeserializeException.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverter.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/UnknownResponseException.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/InfrastructureServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverterTest.java
Labels: Major Change, Status: Pull-Request, Status: Under Review, Type: Enhancement
