Repository International-Data-Spaces-Association/IDS-Messaging-Services, pull requests merged in 2021-07, with the labels that each got.

#192 190 log level changes
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigContainer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/EndpointService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/MessageController.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverter.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/mapping/ArtifactResponseMAP.java
Labels: Status: Pull-Request, Type: Enhancement

#193 License header plugin
  CHANGELOG.md
  broker/pom.xml
  clearinghouse/pom.xml
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/package-info.java
  core/pom.xml
  messaging/pom.xml
  messaging/src/test/java/de/fraunhofer/ids/messaging/endpoint/EndpointServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/InfrastructureServiceTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverterTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/response/MessageResponseTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/IdsMessageUtilsTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/InfomodelMessageBuilderTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/RequestUtilsTest.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/util/SerializerProviderTest.java
  pom.xml
  scripts/ci/license/header.txt
Labels: Status: Pull-Request, Type: Enhancement

#194 fix: KeyStoreManager: look up absolute path at system scope
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  pom.xml
Labels: Status: Under Review, Type: Bug

#196 Forwarding of token claims
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcher.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/handler/message/MessageAndClaimsHandler.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/exceptions/IdsRequestException.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/testhandlers/NotificationMessageHandler.java
  messaging/src/test/java/de/fraunhofer/ids/messaging/dispatcher/testhandlers/RequestMessageHandler.java
  pom.xml
Labels: Status: Feedback Needed

#199 Create an Interface to customize ConfigProducer
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducerInterceptorException.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/PostConfigProducerInterceptor.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/PreConfigProducerInterceptor.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/config/ConfigProducerTest.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/config/PostConfigInterceptor.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/config/PreConfigInterceptor.java
Labels: Status: Feedback Needed

#207 Set correct payload in subject methods of IdsRequestBuilder. Don't send payload in unavailable messages in BrokerService
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/BrokerService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/IdsRequestBuilder.java
Labels: Status: Pull-Request

#213 Nullcheck operation and protocoltype in requestbuilders, throw SendMessageException with Information when one if them is null
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/SendMessageException.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/AccessTokenRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/AppRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ArtifactRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/CommandRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ConnectorCertificateRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ConnectorRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ContractOfferRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ContractRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ContractSupplementRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/DescriptionRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/IdsRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/LogRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ParticipantCertificateRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ParticipantRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/QueryRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ResourceRequestBuilder.java
Labels: Status: Pull-Request, Type: Bug, Type: Enhancement

#215 feat: fullTextSearchBroker remove quotation marks around searchTerm
  CHANGELOG.md
  broker/src/main/java/de/fraunhofer/ids/messaging/broker/BrokerService.java
Labels: Status: Pull-Request, Type: Enhancement

#214 chore: update infomodel artifacts dependencies
  CHANGELOG.md
  pom.xml
Labels: Major Change, Status: Pull-Request, Type: Maintenance

#223 docs: update readme for new Services
  README.md
Labels: Status: Pull-Request, Type: Documentation
