Repository International-Data-Spaces-Association/IDS-Messaging-Services, pull requests merged in 2021-08, with the labels that each got.

#236 Fix vulnerable transitive dependencies.
  CHANGELOG.md
  messaging/pom.xml
  pom.xml
Labels: Status: Feedback Needed, Status: Pull-Request, Type: Maintenance, dependencies

#241 refactor: certifacte error/warning logs
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/TokenProviderService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  pom.xml
Labels: Type: Enhancement, Status: Pull-Request

#245 chore: update infomodel artifacts to 4.2.0
  CHANGELOG.md
  README.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ClientProvider.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigContainer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/util/CertificateSubjectCnProvider.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/util/package-info.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/TokenProviderService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/MessageController.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  pom.xml
Labels: Status: Pull-Request, Major Change

#255 feat: extend FullTextQuery template
  CHANGELOG.md
  messaging/src/main/java/de/fraunhofer/ids/messaging/util/FullTextQueryTemplate.java
  pom.xml
Labels: Type: Feature, Status: Under Review

#257 refactor: KeyStoreManager and ConfigProducer logs
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  pom.xml
Labels: Type: Enhancement, Status: Pull-Request

#260 refactor: log messages
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ClientProvider.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsValidator.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/TokenProviderService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/orbiter/OrbiterTokenManagerService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcher.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/MessageController.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/MessageService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverter.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/util/IdsMessageUtils.java
Labels: Type: Enhancement, Status: Under Review

#269 refactor: logs message reason formats
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ClientProvider.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigContainer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ConfigProducer.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/DapsVerifier.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/TokenProviderService.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/daps/aisec/AisecTokenManagerService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/dispatcher/MessageDispatcher.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/EndpointService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/endpoint/MessageController.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/multipart/MultipartResponseConverter.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/util/IdsMessageUtils.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/util/RequestUtils.java
Labels: Type: Enhancement, Status: Pull-Request

#270 build(deps): bump infomodel-artifacts from 4.2.0 to 4.2.1
  CHANGELOG.md
  README.md
  pom.xml
Labels: Type: Maintenance, Status: Pull-Request
