Repository International-Data-Spaces-Association/IDS-Messaging-Services, pull requests merged in 2021-09, with the labels that each got.

#276 Add new Clearinghouse Endpoint for registering PIDs
  CHANGELOG.md
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseService.java
  clearinghouse/src/main/java/de/fraunhofer/ids/messaging/clearinghouse/IDSClearingHouseService.java
  clearinghouse/src/test/java/de/fraunhofer/ids/messaging/clearinghouse/ClearingHouseServiceTest.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/RequestTemplateProvider.java
  pom.xml
Labels: Status: Feedback Needed, Status: Pull-Request, Major Change

#278 fix: response codes outside 200-299 provoke IOExceptions
  CHANGELOG.md
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
Labels: Type: Bug, Status: Pull-Request

#279 refactor: remove not yet supported useIDSCP and useLDP
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/AccessTokenRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/AppRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ArtifactRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/CommandRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ConnectorCertificateRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ConnectorRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ContractOfferRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ContractRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/DescriptionRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/LogRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ParticipantCertificateRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ParticipantRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/QueryRequestBuilder.java
  messaging/src/main/java/de/fraunhofer/ids/messaging/requests/builder/ResourceRequestBuilder.java
Labels: Type: Maintenance, Status: Pull-Request

#289 chore: update infomodel artifacts 4.2.1 -> 4.2.3
  CHANGELOG.md
  pom.xml
Labels: dependencies

#286 feat: log-debug outgoing messages
  CHANGELOG.md
  messaging/src/main/java/de/fraunhofer/ids/messaging/protocol/http/IdsHttpService.java
Labels: Type: Enhancement, Status: Pull-Request

#291 feat: check if keystore-location is null on init
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManager.java
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ssl/keystore/KeyStoreManagerInitializationException.java
Labels: Type: Enhancement, Status: Pull-Request

#285 feat: validity check for proxy hostname
  CHANGELOG.md
  core/src/main/java/de/fraunhofer/ids/messaging/core/config/ClientProvider.java
  core/src/test/java/de/fraunhofer/ids/messaging/core/config/ConfigProducerTest.java
Labels: Type: Enhancement, Status: Pull-Request

#302 build(deps): bump spring dependencies
  CHANGELOG.md
  messaging/pom.xml
  pom.xml
Labels: dependencies

#303 build(pom): exclude jena-core 4.1.0 use 4.2.0 instead
  CHANGELOG.md
  pom.xml
Labels: Type: Maintenance, Status: Pull-Request, dependencies

#314 build(deps): bump spring-boot-starter dependencies from 2.5.4 to 2.5.5
  CHANGELOG.md
  pom.xml
Labels: dependencies
